# fly.toml app configuration file generated for redwood-test-project on 2023-07-13T15:00:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redwood-test-project"
primary_region = "sjc"

[build]
  build-target = "serve"

[processes]
  api = "/app/node_modules/.bin/rw-server api"
  web = "/app/node_modules/.bin/rw-server web --apiHost http://0.0.0.0:8911"

[env]
  REDWOOD_DISABLE_TELEMETRY = "1"

[[services]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[services]]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["api"]
