#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
# - name: test-project-docker-web
#   type: web
#   runtime: docker
#   dockerfilePath: ./Dockerfile.web
#   branch: render

#   env: static
#   # buildCommand: yarn install && yarn rw deploy render web
#   staticPublishPath: ./web/dist
#   envVars:
#   - key: NODE_VERSION
#     value: 16
#   - key: SKIP_INSTALL_DEPS
#     value: true
#   routes:
#   - type: rewrite
#     source: /.redwood/functions/*
#####
# NOTE: replace destination api url after first deploy to Render
# example:
#   destination: https://myredwoodproject-api.onrender.com/*
#####
  #   destination: replace_with_api_url/*
  # - type: rewrite
  #   source: /*
  #   destination: /index.html

- name: test-project-docker-api
  type: web

  runtime: docker
  dockerfilePath: ./Dockerfile.api

  plan: free
  region: oregon

  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: test-project-docker-db
      property: connectionString

databases:
  - name: test-project-docker-db
    region: oregon

